<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" name="mecanum" xmlns:ignition="http://gazebosim.org/schema">

<!-- <xacro:include filename="hokuyo_ust10.xacro" /> -->
<xacro:property name="radius" value="0.05" />
<xacro:property name="length" value="0.06" />
<xacro:property name="box_length" value="0.3" />
<xacro:property name="box_width" value="0.2" />
<xacro:property name="box_height" value="0.09" />

<material name="blue">
 <color rgba="0 0 0.8 1" />
</material>
<material name="yellow">
 <color rgba="0.8 0.8 0 1.0" />
</material>
<material name="black">
 <color rgba="0 0 0 1" />
</material>
<material name="white">
 <color rgba="1 1 1 1" />
</material>

<link name="front_right_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <mesh filename="file://$(find mecanum_simulation_github)/meshes/Mecanum_jo.stl" scale="0.0010 0.0010 0.0010" />
        </geometry>
        <material name="black" />
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <cylinder length="${length}" radius="${radius}" />
        </geometry>
    </collision>

    <inertial>
        <mass value="0.3"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
</link>
<joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_right_wheel" />
    <origin xyz="0.1 -${box_width/2+length/2} -0.03" />
    <axis xyz="0 1 0" />
</joint>


<link name="front_left_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <mesh filename="file://$(find mecanum_simulation_github)/meshes/Mecanum_jo.stl" scale="0.0010 0.0010 0.0010" />
        </geometry>
        <material name="black" />
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <cylinder length="${length}" radius="${radius}" />
        </geometry>
    </collision>

    <inertial>
        <mass value="0.3"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
</link>
<joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_left_wheel" />
    <origin xyz="0.1 ${box_width/2+length/2} -0.03" />
    <axis xyz="0 1 0" />
</joint>


<link name="rear_left_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <mesh filename="file://$(find mecanum_simulation_github)/meshes/Mecanum_jo.stl" scale="0.0010 0.0010 0.0010" />
        </geometry>
        <material name="black" />
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <cylinder length="${length}" radius="${radius}" />
        </geometry>
    </collision>

    <inertial>
        <mass value="0.3"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
</link>
<joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="rear_left_wheel" />
    <origin xyz="-0.1 ${box_width/2+length/2} -0.03" />
    <axis xyz="0 1 0" />
</joint>

    
<link name="rear_right_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <mesh filename="file://$(find mecanum_simulation_github)/meshes/Mecanum_jo.stl" scale="0.0010 0.0010 0.0010" />
        </geometry>
        <material name="black" />
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.57075 0 0"  />
        <geometry>
            <cylinder length="${length}" radius="${radius}" />
        </geometry>

    </collision>
    <inertial>
        <mass value="0.3"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
</link>
<joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="rear_right_wheel" />
    <origin xyz="-0.1 -${box_width/2+length/2} -0.03" />
    <axis xyz="0 1 0" />
</joint>

<link name="base_link">
    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"  />
        <geometry>
            <box size="${box_length} ${box_width} ${box_height}" />
        </geometry>
        <material name="yellow" />
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"  />
        <geometry>
            <box size="${box_length} ${box_width} ${box_height}" />
        </geometry>
    </collision>
    <inertial>
        <origin xyz="-0.02 0 0.035" rpy="0 0 0" />
        <mass value="3.0" />
        <inertia ixx="0.0300" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
</link>

<link name="base_footprint" />

<joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 0.05" rpy="0 0 0" />
</joint>

<link name="base_scan">
    <visual>
        <origin xyz="0 0 -0.05" rpy="0 0 0"  />
        <geometry>
            <mesh filename="file://$(find mecanum_simulation_github)/meshes/sensors/hokuyo_ust10.stl" scale="0.8 0.8 0.8" />
        </geometry>
        <material name="white" />
    </visual>
    <collision>
        <origin xyz="0 0 -0.0215" rpy="0 0 0" /> 
        <geometry>
            <cylinder length="0.055" radius="0.035" />
        </geometry>
    </collision>
    <inertial>
        <mass value="0.178"/>
        <origin xyz="0 0 0" /> 
        <inertia ixx="1.1e-04" ixy="-1.56e-04" ixz="-3.12e-04" iyy="1.85e-04" iyz="-2.23e-04" izz="2.21e-04" />
    </inertial>
</link>


<joint name="scan_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_scan" />
    <origin xyz="0.1 0 0.09" rpy="0 0 0" />
</joint>


<gazebo reference="base_scan">
<sensor name="base_scan" type="gpu_lidar">

        <pose relative_to='base_scan'>0 0 0 0 0 0</pose>

        <topic>scan</topic>
        <gz_frame_id>base_scan</gz_frame_id>
        <update_rate>10</update_rate>

        <lidar>

          <scan>

            <horizontal>

              <samples>500</samples>

              <resolution>1</resolution>

              <min_angle>-2.3562</min_angle>

              <max_angle>2.3562</max_angle>

              <!-- <angle_increment>0.0175</angle_increment> -->

            </horizontal>

            <!-- <vertical>

              <samples>1</samples>

              <resolution>1</resolution>

              <min_angle>0</min_angle>

              <max_angle>0</max_angle>

            </vertical> -->

          </scan>

          <range>

            <min>0.120</min>

            <max>10.0</max>

            <resolution>0.25</resolution>

          </range>
          <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.02</stddev>
          </noise>
          <frame_id>base_scan</frame_id>
        </lidar>
        <always_on>1</always_on>
        <visualize>true</visualize>
        
      </sensor>     

</gazebo>
<!-- <gazebo>

    <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">

        <render_engine>ogre</render_engine>

    </plugin>
</gazebo> -->
<gazebo>
    <plugin
      filename="libignition-gazebo-mecanum-drive-system.so"
      name="ignition::gazebo::systems::MecanumDrive">
      <!-- Topic for the command input -->
      <topic>/cmd_vel</topic>

      <!-- Wheel joints -->
      <front_left_joint>front_left_wheel_joint</front_left_joint>
      <front_right_joint>front_right_wheel_joint</front_right_joint>
      <back_left_joint>rear_left_wheel_joint</back_left_joint>
      <back_right_joint>rear_right_wheel_joint</back_right_joint>

      <!-- Wheel parameters -->
      <wheel_separation>0.3</wheel_separation>
      <wheelbase>0.3</wheelbase>
      <wheel_radius>0.1</wheel_radius>

      <!-- Control gains and limits (optional) -->
      <min_acceleration>-5</min_acceleration>
      <max_acceleration>5</max_acceleration>

      <!-- Other parameters (optional) -->
      <odom_topic>odom</odom_topic>
      <tf_topic>tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
      <odom_publish_frequency>30</odom_publish_frequency>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
    </plugin>

    <plugin name="ignition::gazebo::systems::OdometryPublisher" filename="libignition-gazebo-odometry-publisher-system">
      <odom_topic>odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
      <publish_tf>true</publish_tf>
      <tf_topic>tf</tf_topic>
      <odom_publish_frequency>30</odom_publish_frequency>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
    </plugin>

    <plugin
        filename="libignition-gazebo-joint-state-publisher-system"
        name="ignition::gazebo::systems::JointStatePublisher">
        <topic>joint_states</topic>
        <joint_name>front_left_wheel_joint</joint_name>
        <joint_name>front_right_wheel_joint</joint_name>
        <joint_name>rear_left_wheel_joint</joint_name>
        <joint_name>rear_right_wheel_joint</joint_name>
    </plugin>

</gazebo>
<gazebo reference="front_right_wheel">
    <collision>
        <surface>
            <friction>
                <ode>
                    <mu1>1.5</mu1>
                    <mu2>0</mu2>
                    <fdir1 ignition:expressed_in="base_footprint">1 1 0</fdir1>
                </ode>
            </friction>
        </surface>
    </collision>
    <kp>500000.0</kp>
    <kd>100.0</kd>
    <maxVel>0.5</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/Black</material>
</gazebo>
<gazebo reference="front_left_wheel">
    <collision>
        <surface>
            <friction>
                <ode>
                    <mu1>1.5</mu1>
                    <mu2>0</mu2>
                    <fdir1 ignition:expressed_in="base_footprint">1 -1 0</fdir1>
                </ode>
            </friction>
        </surface>
    </collision>
    <kp>500000.0</kp>
    <kd>100.0</kd>
    <maxVel>0.5</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="rear_right_wheel">
    <collision>
        <surface>
            <friction>
                <ode>
                    <mu1>1.5</mu1>
                    <mu2>0</mu2>
                    <fdir1 ignition:expressed_in="base_footprint">1 -1 0</fdir1>
                </ode>
            </friction>
        </surface>
    </collision>
    <kp>500000.0</kp>
    <kd>100.0</kd>
    <maxVel>0.5</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="rear_left_wheel">
    <collision>
        <surface>
            <friction>
                <ode>
                    <mu1>1.5</mu1>
                    <mu2>0</mu2>
                    <fdir1 ignition:expressed_in="base_footprint">1 1 0</fdir1>
                </ode>
            </friction>
        </surface>
    </collision>
    <kp>500000.0</kp>
    <kd>100.0</kd>
    <maxVel>0.5</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="base_link">
    <material>Gazebo/Yellow</material>
    <mu1>0.000002</mu1>
    <mu2>0.000002</mu2>
  </gazebo>

  
</robot>